### ISSUE TITLE
多言語対応について

### ISSUE THREAD

**Issue by TakamasaSugiura** [y-chikada/study_marking_201601#7]
これは質問ですが、インスペクション会のメモに

```
・表示言語については、将来的に言語切替の変更要望が行われても、追加実装が容易な形での実装とする。
```

とあります。
現在のコードを多言語対応するとなったときに、どこをどのように変えますか？

**Comment by y-chikada** [comment]
日本語、英語等の言語選択の定数、およびその言語に対応した
曜日配列、表示月配列、メッセージ文字列をコードの先頭に定義します。
次に、曜日表示（日、San）、タイトル年月（2016年1月、2016 Jan）、
日付クリック時メッセージの各項目にどの言語を使用するかを定義した定数を用いて設定します。
html要素作成時、switch文で言語設定に応じて上記の定義配列、メッセージを各項目に代入します。

**Comment by TakamasaSugiura** [comment]
対応を確認しました。
が、現在の書き方ですと、言語が増えたときや言語の切り替えの時に、
ちょっと大変です。(理由は後述)
以下の指摘事項をもとに、改良案を検討してみてください。

## 

まず、言語の切り替え用に変数が用意されていますが・・・

``` Javascript
  var dayLang = ENGLISH_MODE; // 曜日表示言語
  var monthLang = ENGLISH_MODE; // 年月表示言語
  var clickMesLang = ENGLISH_MODE; // 日付クリックメッセ―ジ言語
```

細かく設定できるように、という配慮で3つ用意してあるのだと思いますが、
ここまで細かくする必要はありません。普通は英語だったらすべて英語、フランス語だったらすべてフランス語で見たいと思います。
(Windowsの言語切り替えや、Webブラウザの言語切り替えなどを見てください。
「メニューバーのみ日本語で、その他は英語、とかできないはずです。」)
変数が3つあると、言語切り替えの時に3か所直さないといけないので、ちょっと面倒です。

## 

この3変数につられて、言語ごとの処理を行う場所が3か所に分かれています。
これはよくありません。
言語を増やすたびに、3か所に記述を追加しないといけないので、面倒です。
場所もバラバラなので、直し忘れる恐れもあります。
言語ごとの処理は一か所にまとめておいて、
追加する際にブロック丸ごとコピー＆編集ができるようにしておくと、
言語追加の時のミスも少なくなります。

**Comment by TakamasaSugiura** [comment]
確認しました。
バラバラになっていた言語切り替え処理が一つにまとまっているのでＯＫです。
@c74f19b

## 

なお、ここからは細かいことになりますので、好みが分かれるところですが、
もし気に入ったら参考にしてください。
1. 月の作成処理が日本語と英語で別々の作り(日本語版は「○○月」を作成、英語版は配列から取得)になっていますが、配列から取得のような形に統一したほうが、他人に頼んだ翻訳を当て込みやすい。(自身が何か国語も使えるスーパーエンジニアならともかく、そうでないのであれば、翻訳は誰かに頼んで、ということになります。)英語の月配列なども、そとだしにしないで、switch(langMode)内で完結したほうがいいでしょう。ただし、記述が冗長になる欠点があります。なお、日本語でも、「睦月、如月、弥生・・・」という表記にする場合は、配列型にせざるを得なくなりますね。
2. 関数の結果をグローバル変数にセットするか、返り値にするかというのがちょくちょく問題になります。今回の場合は、「ページ全体の表示を切り替える」ということで、グローバル変数セットでも違和感ありません。
